# Generated by Django 4.2 on 2024-03-12 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='duration',
            field=models.PositiveIntegerField(default=60),
        ),
    ]
