# Generated by Django 4.2 on 2024-04-01 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0003_meeting_isinviteeresponsereceived'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
