# Generated by Django 4.2 on 2024-04-02 02:34

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
        ('schedules', '0004_schedule_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='color',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='meeting',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='meeting',
            name='invitee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contacts.contact'),
        ),
    ]
