# Generated by Django 4.2 on 2024-04-02 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0005_meeting_color_meeting_date_meeting_invitee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='date',
            field=models.CharField(default='April 1, 2024', max_length=50),
        ),
    ]
