# Generated by Django 4.2 on 2024-04-02 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0007_alter_meeting_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='color',
            field=models.CharField(blank=True, default='#FFCC99', max_length=20),
        ),
    ]
