# Generated by Django 4.2 on 2024-04-02 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0009_alter_meeting_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='color',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
