# Generated by Django 4.2 on 2024-04-03 06:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0010_alter_meeting_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='isArchived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='schedule',
            name='start_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
