# Generated by Django 4.2 on 2024-04-06 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0011_schedule_isarchived_schedule_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='color',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
