# Generated by Django 4.2 on 2024-04-07 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invites", "0002_alter_invite_date_sent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invite",
            name="date_sent",
            field=models.DateField(default="2024-04-07"),
        ),
    ]
